version: '3'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

  prisma:
    build:
      context: ./
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/database?schema=public
    depends_on:
      - db
    ports:
      - '3000:3000'
